apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: mycluster
 region: us-east-1

managedNodeGroups:
 - name: mynode-1
   instanceType: t3.medium
   spot: true
   minSize: 2
   maxSize: 2
   desiredCapacity: 2
   ssh:
    publicKeyName: testkey