---
apiVersion: v1
kind: Pod
metadata:
 name: catalogue
 labels:
  tier: backend
spec:
 containers:
  - image: srikanthhg/catalogue:k8
    name: catalogueimage
    resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
       cpu: "100m"
       memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
 name: catalogue
spec:
 selector:
  tier: backend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  