---
apiVersion: v1
kind: Pod
metadata:
 name: mongodb
 labels:
  tier: db
spec:
 containers:
  - image: srikanthhg/mongodb:k8
    name: mydb
    imagePullPolicy: Always
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb-service
spec:
 selector:
  tier: db
 ports:
  - protocol: TCP
    port: 80
    targetPort: 27017 